=== cheefoei/FioreFlowershop/resources/Customer.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT customers (customer+)>
<!ELEMENT customer (name, email, phone, address, monthlyCreditLimit?)>
<!ATTLIST customer customerID ID #REQUIRED>
<!ATTLIST customer type (Consumer | Corporate ) #REQUIRED>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT monthlyCreditLimit (#PCDATA)>

=== cheefoei/FioreFlowershop/resources/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE customers SYSTEM 'Customer.dtd'>
<customers>
    <customer customerID="C001" type="corporate">
        <name>
            <fname>Chris</fname>
            <lname>Evans</lname>
        </name>
        <email>cap@email.com</email>
        <phone>013-5647895</phone>
        <address>7, Jalan Malinja 2, Taman Bunga Raya, 53000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur</address>
        <monthlyCreditLimit>1000.00</monthlyCreditLimit>
    </customer>
</customers>
